# Generated by Django 5.2.4 on 2025-07-04 15:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas', '0003_receita'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='tabelas.consulta'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ReceitaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosagem', models.CharField(max_length=45)),
                ('frequencia', models.CharField(max_length=45)),
                ('duracao', models.CharField(max_length=45)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='tabelas.receita')),
            ],
        ),
    ]
