# Generated by Django 5.2.4 on 2025-07-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelas', '0004_receita_consulta_alter_consulta_data_hora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=250)),
            ],
        ),
    ]
